### ISSUE TITLE
Update pypi version

### ISSUE THREAD

**Issue by shadow1runner** [rhijjawi/NextDNS-API#10]
Could you please push an updated version (which also includes #8) to PyPi? Just having installed the latest version doesn't feature the `rewrite` options, thanks!

```shell
>>> settings.
settings.blockpage(       settings.delete(          settings.logclientips(    settings.mro(             settings.setup(
settings.clearlogs(       settings.listsettings(    settings.logdomains(      settings.rename(          settings.updatelinkedip(
```

**Comment by rhijjawi** [comment]
Sure, at the airport right now, will @ mention you when I push to pypi.

**Comment by jmelett** [comment]
@rhijjawi any chance you could push to pypi? thanks!

**Comment by rhijjawi** [comment]
@jmelett Mind helping with that? I seem to have forgotten how to upload to pypi.

**Comment by MadhavVij** [comment]
@rhijjawi  There are multiple ways for publishing packages to PyPi, all of them require you to authenticate with your PyPi account and publish the repository.

Real Python has a great guide on publishing packages in multiple ways.
https://realpython.com/pypi-publish-python-package/

**Comment by rhijjawi** [comment]
@MadhavVij, @jmelett, @shadow1runner and others. Glad to let you release 1.8.0 is now on PyPI.
