### ISSUE TITLE
[Bug/Issue] can't get any response

### ISSUE THREAD

**Issue by aviv926** [rhijjawi/NextDNS-API#14]
**Describe the bug**
Maybe I'm missing something?
I can't get any response when I run the code

**To Reproduce**
Run the first lines in code example of doc with your username + password

**Expected behavior**
response 

**Screenshots**
![image](https://github.com/rhijjawi/NextDNS-API/assets/51673860/d97d0be5-f61c-411f-bfd1-47999765a1ba)

**Desktop (please complete the following information):**
 - OS: WIN 10
 - Version last

**Comment by rhijjawi** [comment]
Hey @aviv926!
Thank you for opening an issue on the repo. In Python, as long as code is not running in the interpreter on cmd, you actually have to print() everything you want to see in the terminal. 
Let me know if this helped.

**Comment by aviv926** [comment]
> Hey @aviv926! Thank you for opening an issue on the repo. In Python, as long as code is not running in the interpreter on cmd, you actually have to print() everything you want to see in the terminal. Let me know if this helped.

Problem solved, thank you!
