### ISSUE TITLE
allowlist.add() returns {'error': 'required'}

### ISSUE THREAD

**Issue by jinkang23** [rhijjawi/NextDNS-API#2]
When I run the following command (using my config id):

` allowlist.add("krunker.io", "d46a5b", header)`

It returns the following error:
`{'error': 'required'}`

My credentials are fine and I'm able run `allowlist.list()` and `allowlist.remove()` 

@rhijjawi  - Since these APIs are undocumented, it's hard to tell what's causing this error. Any idea what needs to change for the API to work? Thanks!

**Comment by rhijjawi** [comment]
Sorry for taking a while to close this issue. I actually thought I had already replied to it. This issue has been patched.
